### ISSUE TITLE
Utility AI functional examples?

### ISSUE THREAD

**Issue by zircher** [TheDuriel/DurielsGodotUtilities#1]
I'm new to Godot and wanting to learn more about Utility AI for a future project.  The scripts look interesting, but I need a little bit more either a functioning project to see how these are are correctly used or (wishfully) a detailed tutorial on their usage.  Is there something like that out there can can be shared or included with this package?

**Comment by TheDuriel** [comment]
This is definitely not a functional system and more of a code example sorry. Most of the contents of this repo I copy and paste into my projects and then build fresh systems on top. I might recycle the utility ai basis presented here in the near future for an RPG I am working on.

**Comment by zircher** [comment]
Okie dokie, thanks for the insight.  I guess I'll have to sort it out and modify it as I learn more about godot programming.  I'll add a watch to GIT in case an update drops.  Thanks for the fast reply.
